server:
  port: 8000

eureka:
  instance:
    hostname: localhost
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka

spring:
  application:
    name: apigateway-service
  cloud:
    gateway:
      discovery:
        locator:
          lower-case-service-id: true
          enabled: true
      routes:
        - id: auth-service
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/auth-service/**
            - Method=POST,GET

        - id: web-service
          uri: lb://WEB-SERVICE
          predicates:
            - Path=/web-service/**
            - Method=POST,GET
          filters:
            - RemoveRequestHeader=Cookie
            #- AuthorizationHeaderFilter # JWT 검증을 위한 Custom GatewayFilter
            - RewritePath=/web-service/?(?<segment>.*), /$\{segment}

        - id: stock-service
          uri: lb://STOCK-SERVICE
          predicates:
            - Path=/stock-service/**
            - Method=POST,GET
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/stock-service/?(?<segment>.*), /$\{segment}
