server:
  port: 8000

eureka:
  instance:
    hostname: localhost
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka

spring:
  application:
    name: apigateway-service
  cloud:
    gateway:
      discovery:
        locator:
          lower-case-service-id: true
          enabled: true
      routes:
        - id: web-service
          uri: lb://WEB-SERVICE
          predicates:
            - Path=/web-service/**
            - Method=POST,GET
        - id: stock-service
          uri: lb://STOCK_SERVICE
          predicates:
            - Path=/stock-service/**
            - Method=POST,GET
            #https://github.com/wkd-woo/msa-spring-ecommerce/blob/main/apigateway-service/src/main/resources/application.yml
